### ISSUE TITLE
Chat scrolling

### ISSUE THREAD

**Issue by Alec123445** [mrtwidget/Livemaps#1]
when using scroll bar with chat having alot of lines in it moving it a pixel up or down moves it 20 something lines. Scrolling with a scroll wheel in free scroll (no resistance) takes 30 seconds to scroll from top to bottom.
Chat box displays when chat is empty. Maybe make it not visible when its empty?

**Comment by mrtwidget** [comment]
**Confirmed.**

The scrolling issue seems to be a problem with the custom scrollbar plugin I'm using [[see more]](https://github.com/malihu/malihu-custom-scrollbar-plugin). I will need to either refine its implementation, or scrap it and customize it myself. 

As for the chat displaying when it's empty, I have resolved this on the [development page](http://nexisrealms.com/dev/Livemaps) and have added it to my next commit.

Thank you for the feedback, @Alec123445
