### ISSUE TITLE
Massive amounts of random player heads

### ISSUE THREAD

**Issue by Alec123445** [mrtwidget/Livemaps#2]
https://www.youtube.com/watch?v=y-bM6gVbWBQ
This happens when i switch tabs in chrome and click out of chrome, and seems that if the aboves true then it has to be more than 10ish players.

**Comment by mrtwidget** [comment]
**Confirmed.**

I have noticed this too, and am investigating currently. It seems as though, for whatever reason, the nodes are being duplicated.

http://prntscr.com/fmwasd

**Comment by mrtwidget** [comment]
This has been repaired in the newest commit.
