### ISSUE TITLE
Plugin doesn't initialize.

### ISSUE THREAD

**Issue by Zibbp** [mrtwidget/Livemaps#3]
Hello, I have compiled the livemap.dll via livemap.cs in Visual Studio and dropped it into my plugins folder. When I go ahead and turn on the server it doesn't recognize the plugin at all.

**Comment by mrtwidget** [comment]
@zippy4 
Could you please be more specific? You said you compiled using the Livemap.cs file? The project should be compiled using the `Livemap.sln` file:

![image](https://user-images.githubusercontent.com/2043476/27773131-d1334636-5f40-11e7-894e-6ccc4f6baa36.png)

The website related files for this project are also highlighted above, but are not necessary when compiling the project.

Are you able to forward any logs during your attempt? Are you running Linux or Windows? Are you using the current version of Rocket Mod? 

Thanks for your feedback, @zippy4! I look forward to hearing back from you.

**Comment by Zibbp** [comment]
@mrtwidget 
I compiled the Livemap.dll via the .sln then dropped it into my rocket plugins directory, upon the server loading this error pops up:
![](https://i.gyazo.com/78840c90f0f74ae7f3d0f8110389e71c.png)
I'm running the latest version of Rocket Mod and server..... If you need anything else like logs or anything just ask.
Thanks.

**Comment by mrtwidget** [comment]
@zippy4 
The error is requesting this file:
![image](https://user-images.githubusercontent.com/2043476/27777055-8b797952-5f7d-11e7-9bca-efe3fbdcfc27.png)

You will need to transfer the files above, which are located in the Libraries folder, to your Rocket Libraries folder:
![image](https://user-images.githubusercontent.com/2043476/27777036-5d80037c-5f7d-11e7-9b10-00f30aa56817.png)

If this resolves your issue, please feel free to close this topic. :+1:

**Comment by Zibbp** [comment]
@mrtwidget 
I added the .DLL file into the Libraries folder and now I am receiving a new error.
![](https://i.gyazo.com/8cbb2932a76fa21cb500215c3d67a3d9.png)
Thanks for all the quick support.

**Comment by mrtwidget** [comment]
@zippy4 
Please confirm you have updated your plugin config file with your MySQL credentials, and that all three(3) tables were successfully created: [livemap_server, livemap_data, livemap_chat]

**Comment by Zibbp** [comment]
@mrtwidget That was the fix! Thanks for the awesome and quick support!!
