### ISSUE TITLE
Error reading Steam Profile

### ISSUE THREAD

**Issue by DrFrostie** [mrtwidget/Livemaps#7]
I am running into a little issue with Steam Profiles not being able to read. I believe it's a quick fix, let me know if you are able to help.

![dwdwd](https://user-images.githubusercontent.com/23130561/47260984-9f638c00-d47a-11e8-9717-2dd0abf07438.PNG)

- Dr. Frostie

**Comment by DrFrostie** [comment]
Another Error has popped up now. I really just don't know why it's doing this.

![captudsdre](https://user-images.githubusercontent.com/23130561/47396324-1b5e0e00-d6df-11e8-87c5-ac91054b70f2.PNG)

**Comment by mrtwidget** [comment]
Fixing this now.

**Comment by mrtwidget** [comment]
This has been fixed in v0.3
